receivers:
  statsd:
    endpoint: "localhost:8125"
    transport: "udp4"
    aggregation_interval: 70s
    enable_metric_type: false
    timer_histogram_mapping:
      - statsd_type: "histogram"
        observer_type: "gauge"
      - statsd_type: "timing"
        observer_type: "histogram"
        histogram:
          max_size: 170
      - statsd_type: "distribution"
        observer_type: "summary"
        summary:
          percentiles: [0, 10, 50, 90, 95, 100]

service:
  pipelines:
    metrics:
      receivers: [statsd]
      exporters: [debug]
      processors: []

exporters:
  debug:
    verbosity: detailed
    sampling_initial: 1
    sampling_thereafter: 200